name: WanderingTrader
version: ${project.version}
main: su.brim.WanderingTraderPlugin
api-version: '1.21'
folia-supported: true
description: Custom Wandering Trader trades for worlds without Nether access
author: WanderingTrader

commands:
  wanderingtrader:
    description: WanderingTrader admin commands
    usage: /<command> <reload|list|info>
    aliases: [wt, trader]

permissions:
  wanderingtrader.admin:
    description: Access to all Wandering trader commands
    default: op
